//Programmes Offered

export const pricing_details = [
    {
        id:1,
        level:1,
        amount:250,
        description:'FOR THREE MONTHS OR $700 ONE TIME FEE',
        selected:false,
        plan:'',
        quantity:1,
        purchasedOn:'',
    },
    {
        id:2,
        level:2,
        amount:250,
        description:'FOR THREE MONTHS OR $700 ONE TIME FEE',
        selected:false,
        plan:'',
        quantity:1,
        purchasedOn:'',
    },
    {
        id:3,
        level:3,
        amount:250,
        description:'FOR THREE MONTHS OR $700 ONE TIME FEE',
        selected:false,
        plan:'',
        quantity:1,
        purchasedOn:'',
    },
    {
        id:4,
        level:4,
        amount:250,
        description:'FOR THREE MONTHS OR $700 ONE TIME FEE',
        selected:false,
        plan:'',
        quantity:1,
        purchasedOn:'',
    },
    {
        id:5,
        level:5,
        amount:250,
        description:'FOR THREE MONTHS OR $700 ONE TIME FEE',
        selected:false,
        plan:'',
        quantity:1,
        purchasedOn:'',
    },
]